//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Papi.Negkas.MusicClassroom.Ux.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Papi.Negkas.MusicClassroom.Ux.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap chordDoMajorBig {
            get {
                object obj = ResourceManager.GetObject("chordDoMajorBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chordfaAugBig {
            get {
                object obj = ResourceManager.GetObject("chordfaAugBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap chordLaMinorBig {
            get {
                object obj = ResourceManager.GetObject("chordLaMinorBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1253\uc1\adeff31507\deff0\stshfdbch0\stshfloch31506\stshfhich31506\stshfbi31506\deflang1032\deflangfe1032\themelang1032\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset161\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f2\fbidi \fmodern\fcharset161\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}
        ///{\f34 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Chords {
            get {
                return ResourceManager.GetString("Chords", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap chordsiMinorDimBig {
            get {
                object obj = ResourceManager.GetObject("chordsiMinorDimBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap do_ {
            get {
                object obj = ResourceManager.GetObject("do+", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoBig {
            get {
                object obj = ResourceManager.GetObject("DoBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DoMajorScaleAll {
            get {
                object obj = ResourceManager.GetObject("DoMajorScaleAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap EighthBig {
            get {
                object obj = ResourceManager.GetObject("EighthBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FaBig {
            get {
                object obj = ResourceManager.GetObject("FaBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1253\uc1\adeff31507\deff0\stshfdbch31506\stshfloch31506\stshfhich31506\stshfbi31507\deflang1032\deflangfe1032\themelang1032\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset161\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f2\fbidi \fmodern\fcharset161\fprq1{\*\panose 02070309020205020404}Courier New;}{\f3\fbidi \froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f10\fbidi \fnil\fcharset2\fprq2{\*\panose 05000000000000000000}Wingdings;}
        ///{ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap HalfBig {
            get {
                object obj = ResourceManager.GetObject("HalfBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyAltoBig {
            get {
                object obj = ResourceManager.GetObject("KeyAltoBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeyFaBig {
            get {
                object obj = ResourceManager.GetObject("KeyFaBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap KeySolBig {
            get {
                object obj = ResourceManager.GetObject("KeySolBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LaBig {
            get {
                object obj = ResourceManager.GetObject("LaBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap LaMinorScaleAll {
            get {
                object obj = ResourceManager.GetObject("LaMinorScaleAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MiBig {
            get {
                object obj = ResourceManager.GetObject("MiBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause4thBig {
            get {
                object obj = ResourceManager.GetObject("Pause4thBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause8thBig {
            get {
                object obj = ResourceManager.GetObject("Pause8thBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseBig {
            get {
                object obj = ResourceManager.GetObject("PauseBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseHalfBig {
            get {
                object obj = ResourceManager.GetObject("PauseHalfBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap QuarterBig {
            get {
                object obj = ResourceManager.GetObject("QuarterBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ReBig {
            get {
                object obj = ResourceManager.GetObject("ReBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Είστε σίγουρος πως θέλετε να διαγραφεί η επιλεγμένη ερώτηση;.
        /// </summary>
        internal static string S_QDeleteQuestion {
            get {
                return ResourceManager.GetString("S_QDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Το τεστ ολόκληρώθηκε. O Βαθμός σας είναι {0:N} στα 10.
        /// </summary>
        internal static string S_TestCompleted {
            get {
                return ResourceManager.GetString("S_TestCompleted", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap S16thBig {
            get {
                object obj = ResourceManager.GetObject("S16thBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1253\uc1\adeff31507\deff0\stshfdbch31506\stshfloch31506\stshfhich31506\stshfbi31507\deflang1032\deflangfe1032\themelang1032\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset161\fprq2{\*\panose 02020603050405020304}Times New Roman;}
        ///{\f15\fbidi \fmodern\fcharset128\fprq1{\*\panose 020b0609070205080204}MS Gothic{\*\falt \&apos;82\&apos;6c\&apos;82\&apos;72 \&apos;83\&apos;53\&apos;83\&apos;56\&apos;83\&apos;62\&apos;83\&apos;4e};}{\f34\fbidi \froman\fcharset1\fprq2{\*\panose 02040503050406030204}Cambria Math;}
        ///{\f37\fbidi  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Scales {
            get {
                return ResourceManager.GetString("Scales", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SiBig {
            get {
                object obj = ResourceManager.GetObject("SiBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SolBig {
            get {
                object obj = ResourceManager.GetObject("SolBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webhipreAll {
            get {
                object obj = ResourceManager.GetObject("webhipreAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap webhipreAllnew {
            get {
                object obj = ResourceManager.GetObject("webhipreAllnew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap WholeBig {
            get {
                object obj = ResourceManager.GetObject("WholeBig", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
